//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.09 at 07:55:29 PM EDT 
//


package gov.sbs.devops.puttygenerator.mtputty;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Globals">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PuttyLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="GUI">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Pos">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="Left" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *                                     &lt;attribute name="Top" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *                                     &lt;attribute name="Right" type="{http://www.w3.org/2001/XMLSchema}int" default="1900" />
 *                                     &lt;attribute name="Bottom" type="{http://www.w3.org/2001/XMLSchema}int" default="1100" />
 *                                     &lt;attribute name="Maximized" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ServersBox">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="Visible" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *                                     &lt;attribute name="Width" type="{http://www.w3.org/2001/XMLSchema}int" default="240" />
 *                                     &lt;attribute name="Height" type="{http://www.w3.org/2001/XMLSchema}int" default="1050" />
 *                                     &lt;attribute name="Dock" type="{http://www.w3.org/2001/XMLSchema}string" default="Left" />
 *                                     &lt;attribute name="Autohide" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Toolbar">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="Visible" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="MainMenu">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="Visible" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="StartPage">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="HideOnTab" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="General">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TabCaption" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="NormalTermination" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="AbnormalTermination" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="QuitNoConfirm" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="CloseButtonOnTabs" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Servers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Putty">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Node" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="SavedSession" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="DisplayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ServerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="PuttyConType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="Port" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="PasswordDelay" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="CLParams" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ScriptDelay" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Internals">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Putty" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Recents">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PuttyCon" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Hotkeys">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NextTab" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="PrevTab" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="AppSwitch" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="acPuttyLocations" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="acSettings" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="acHideServers" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="acHideMenu" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="acHideToolbar" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="acAddServer" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="acAddGroup" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="acRemove" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="acDetach" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="acConnect" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="acConnectTo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="acTreeProps" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="acSendScript" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="acAttach" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="acRenameTab" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="acImportTree" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="acExportTree" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="acHotkeyMap" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="acDuplicate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "globals",
    "servers",
    "internals",
    "recents",
    "hotkeys"
})
@XmlRootElement(name = "MTPutty")
public class MTPutty {

    @XmlElement(name = "Globals", required = true)
    protected MTPutty.Globals globals;
    @XmlElement(name = "Servers", required = true)
    protected MTPutty.Servers servers;
    @XmlElement(name = "Internals", required = true)
    protected MTPutty.Internals internals;
    @XmlElement(name = "Recents", required = true)
    protected MTPutty.Recents recents;
    @XmlElement(name = "Hotkeys", required = true)
    protected MTPutty.Hotkeys hotkeys;
    @XmlAttribute(name = "version")
    protected Double version;

    /**
     * Gets the value of the globals property.
     * 
     * @return
     *     possible object is
     *     {@link MTPutty.Globals }
     *     
     */
    public MTPutty.Globals getGlobals() {
        return globals;
    }

    /**
     * Sets the value of the globals property.
     * 
     * @param value
     *     allowed object is
     *     {@link MTPutty.Globals }
     *     
     */
    public void setGlobals(MTPutty.Globals value) {
        this.globals = value;
    }

    /**
     * Gets the value of the servers property.
     * 
     * @return
     *     possible object is
     *     {@link MTPutty.Servers }
     *     
     */
    public MTPutty.Servers getServers() {
        return servers;
    }

    /**
     * Sets the value of the servers property.
     * 
     * @param value
     *     allowed object is
     *     {@link MTPutty.Servers }
     *     
     */
    public void setServers(MTPutty.Servers value) {
        this.servers = value;
    }

    /**
     * Gets the value of the internals property.
     * 
     * @return
     *     possible object is
     *     {@link MTPutty.Internals }
     *     
     */
    public MTPutty.Internals getInternals() {
        return internals;
    }

    /**
     * Sets the value of the internals property.
     * 
     * @param value
     *     allowed object is
     *     {@link MTPutty.Internals }
     *     
     */
    public void setInternals(MTPutty.Internals value) {
        this.internals = value;
    }

    /**
     * Gets the value of the recents property.
     * 
     * @return
     *     possible object is
     *     {@link MTPutty.Recents }
     *     
     */
    public MTPutty.Recents getRecents() {
        return recents;
    }

    /**
     * Sets the value of the recents property.
     * 
     * @param value
     *     allowed object is
     *     {@link MTPutty.Recents }
     *     
     */
    public void setRecents(MTPutty.Recents value) {
        this.recents = value;
    }

    /**
     * Gets the value of the hotkeys property.
     * 
     * @return
     *     possible object is
     *     {@link MTPutty.Hotkeys }
     *     
     */
    public MTPutty.Hotkeys getHotkeys() {
        return hotkeys;
    }

    /**
     * Sets the value of the hotkeys property.
     * 
     * @param value
     *     allowed object is
     *     {@link MTPutty.Hotkeys }
     *     
     */
    public void setHotkeys(MTPutty.Hotkeys value) {
        this.hotkeys = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVersion(Double value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PuttyLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="GUI">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Pos">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="Left" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
     *                           &lt;attribute name="Top" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
     *                           &lt;attribute name="Right" type="{http://www.w3.org/2001/XMLSchema}int" default="1900" />
     *                           &lt;attribute name="Bottom" type="{http://www.w3.org/2001/XMLSchema}int" default="1100" />
     *                           &lt;attribute name="Maximized" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="ServersBox">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="Visible" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
     *                           &lt;attribute name="Width" type="{http://www.w3.org/2001/XMLSchema}int" default="240" />
     *                           &lt;attribute name="Height" type="{http://www.w3.org/2001/XMLSchema}int" default="1050" />
     *                           &lt;attribute name="Dock" type="{http://www.w3.org/2001/XMLSchema}string" default="Left" />
     *                           &lt;attribute name="Autohide" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Toolbar">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="Visible" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="MainMenu">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="Visible" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="StartPage">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="HideOnTab" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="General">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TabCaption" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="NormalTermination" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="AbnormalTermination" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="QuitNoConfirm" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="CloseButtonOnTabs" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "puttyLocation",
        "gui",
        "general"
    })
    public static class Globals {

        @XmlElement(name = "PuttyLocation", required = true, defaultValue = "D:\\tools\\PuTTY\\PUTTY.exe")
        protected String puttyLocation;
        @XmlElement(name = "GUI", required = true)
        protected MTPutty.Globals.GUI gui;
        @XmlElement(name = "General", required = true)
        protected MTPutty.Globals.General general;

        /**
         * Gets the value of the puttyLocation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPuttyLocation() {
            return puttyLocation;
        }

        /**
         * Sets the value of the puttyLocation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPuttyLocation(String value) {
            this.puttyLocation = value;
        }

        /**
         * Gets the value of the gui property.
         * 
         * @return
         *     possible object is
         *     {@link MTPutty.Globals.GUI }
         *     
         */
        public MTPutty.Globals.GUI getGUI() {
            return gui;
        }

        /**
         * Sets the value of the gui property.
         * 
         * @param value
         *     allowed object is
         *     {@link MTPutty.Globals.GUI }
         *     
         */
        public void setGUI(MTPutty.Globals.GUI value) {
            this.gui = value;
        }

        /**
         * Gets the value of the general property.
         * 
         * @return
         *     possible object is
         *     {@link MTPutty.Globals.General }
         *     
         */
        public MTPutty.Globals.General getGeneral() {
            return general;
        }

        /**
         * Sets the value of the general property.
         * 
         * @param value
         *     allowed object is
         *     {@link MTPutty.Globals.General }
         *     
         */
        public void setGeneral(MTPutty.Globals.General value) {
            this.general = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TabCaption" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="NormalTermination" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="AbnormalTermination" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="QuitNoConfirm" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="CloseButtonOnTabs" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tabCaption",
            "normalTermination",
            "abnormalTermination",
            "quitNoConfirm",
            "closeButtonOnTabs"
        })
        public static class General {

            @XmlElement(name = "TabCaption", defaultValue = "0")
            protected int tabCaption;
            @XmlElement(name = "NormalTermination", defaultValue = "0")
            protected int normalTermination;
            @XmlElement(name = "AbnormalTermination", defaultValue = "0")
            protected int abnormalTermination;
            @XmlElement(name = "QuitNoConfirm", defaultValue = "1")
            protected int quitNoConfirm;
            @XmlElement(name = "CloseButtonOnTabs", defaultValue = "1")
            protected int closeButtonOnTabs;

            /**
             * Gets the value of the tabCaption property.
             * 
             */
            public int getTabCaption() {
                return tabCaption;
            }

            /**
             * Sets the value of the tabCaption property.
             * 
             */
            public void setTabCaption(int value) {
                this.tabCaption = value;
            }

            /**
             * Gets the value of the normalTermination property.
             * 
             */
            public int getNormalTermination() {
                return normalTermination;
            }

            /**
             * Sets the value of the normalTermination property.
             * 
             */
            public void setNormalTermination(int value) {
                this.normalTermination = value;
            }

            /**
             * Gets the value of the abnormalTermination property.
             * 
             */
            public int getAbnormalTermination() {
                return abnormalTermination;
            }

            /**
             * Sets the value of the abnormalTermination property.
             * 
             */
            public void setAbnormalTermination(int value) {
                this.abnormalTermination = value;
            }

            /**
             * Gets the value of the quitNoConfirm property.
             * 
             */
            public int getQuitNoConfirm() {
                return quitNoConfirm;
            }

            /**
             * Sets the value of the quitNoConfirm property.
             * 
             */
            public void setQuitNoConfirm(int value) {
                this.quitNoConfirm = value;
            }

            /**
             * Gets the value of the closeButtonOnTabs property.
             * 
             */
            public int getCloseButtonOnTabs() {
                return closeButtonOnTabs;
            }

            /**
             * Sets the value of the closeButtonOnTabs property.
             * 
             */
            public void setCloseButtonOnTabs(int value) {
                this.closeButtonOnTabs = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Pos">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="Left" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
         *                 &lt;attribute name="Top" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
         *                 &lt;attribute name="Right" type="{http://www.w3.org/2001/XMLSchema}int" default="1900" />
         *                 &lt;attribute name="Bottom" type="{http://www.w3.org/2001/XMLSchema}int" default="1100" />
         *                 &lt;attribute name="Maximized" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="ServersBox">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="Visible" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
         *                 &lt;attribute name="Width" type="{http://www.w3.org/2001/XMLSchema}int" default="240" />
         *                 &lt;attribute name="Height" type="{http://www.w3.org/2001/XMLSchema}int" default="1050" />
         *                 &lt;attribute name="Dock" type="{http://www.w3.org/2001/XMLSchema}string" default="Left" />
         *                 &lt;attribute name="Autohide" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Toolbar">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="Visible" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="MainMenu">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="Visible" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="StartPage">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="HideOnTab" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "pos",
            "serversBox",
            "toolbar",
            "mainMenu",
            "startPage"
        })
        public static class GUI {

            @XmlElement(name = "Pos", required = true)
            protected MTPutty.Globals.GUI.Pos pos;
            @XmlElement(name = "ServersBox", required = true)
            protected MTPutty.Globals.GUI.ServersBox serversBox;
            @XmlElement(name = "Toolbar", required = true)
            protected MTPutty.Globals.GUI.Toolbar toolbar;
            @XmlElement(name = "MainMenu", required = true)
            protected MTPutty.Globals.GUI.MainMenu mainMenu;
            @XmlElement(name = "StartPage", required = true)
            protected MTPutty.Globals.GUI.StartPage startPage;

            /**
             * Gets the value of the pos property.
             * 
             * @return
             *     possible object is
             *     {@link MTPutty.Globals.GUI.Pos }
             *     
             */
            public MTPutty.Globals.GUI.Pos getPos() {
                return pos;
            }

            /**
             * Sets the value of the pos property.
             * 
             * @param value
             *     allowed object is
             *     {@link MTPutty.Globals.GUI.Pos }
             *     
             */
            public void setPos(MTPutty.Globals.GUI.Pos value) {
                this.pos = value;
            }

            /**
             * Gets the value of the serversBox property.
             * 
             * @return
             *     possible object is
             *     {@link MTPutty.Globals.GUI.ServersBox }
             *     
             */
            public MTPutty.Globals.GUI.ServersBox getServersBox() {
                return serversBox;
            }

            /**
             * Sets the value of the serversBox property.
             * 
             * @param value
             *     allowed object is
             *     {@link MTPutty.Globals.GUI.ServersBox }
             *     
             */
            public void setServersBox(MTPutty.Globals.GUI.ServersBox value) {
                this.serversBox = value;
            }

            /**
             * Gets the value of the toolbar property.
             * 
             * @return
             *     possible object is
             *     {@link MTPutty.Globals.GUI.Toolbar }
             *     
             */
            public MTPutty.Globals.GUI.Toolbar getToolbar() {
                return toolbar;
            }

            /**
             * Sets the value of the toolbar property.
             * 
             * @param value
             *     allowed object is
             *     {@link MTPutty.Globals.GUI.Toolbar }
             *     
             */
            public void setToolbar(MTPutty.Globals.GUI.Toolbar value) {
                this.toolbar = value;
            }

            /**
             * Gets the value of the mainMenu property.
             * 
             * @return
             *     possible object is
             *     {@link MTPutty.Globals.GUI.MainMenu }
             *     
             */
            public MTPutty.Globals.GUI.MainMenu getMainMenu() {
                return mainMenu;
            }

            /**
             * Sets the value of the mainMenu property.
             * 
             * @param value
             *     allowed object is
             *     {@link MTPutty.Globals.GUI.MainMenu }
             *     
             */
            public void setMainMenu(MTPutty.Globals.GUI.MainMenu value) {
                this.mainMenu = value;
            }

            /**
             * Gets the value of the startPage property.
             * 
             * @return
             *     possible object is
             *     {@link MTPutty.Globals.GUI.StartPage }
             *     
             */
            public MTPutty.Globals.GUI.StartPage getStartPage() {
                return startPage;
            }

            /**
             * Sets the value of the startPage property.
             * 
             * @param value
             *     allowed object is
             *     {@link MTPutty.Globals.GUI.StartPage }
             *     
             */
            public void setStartPage(MTPutty.Globals.GUI.StartPage value) {
                this.startPage = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="Visible" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class MainMenu {

                @XmlAttribute(name = "Visible")
                protected Integer visible;

                /**
                 * Gets the value of the visible property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public int getVisible() {
                    if (visible == null) {
                        return  1;
                    } else {
                        return visible;
                    }
                }

                /**
                 * Sets the value of the visible property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setVisible(Integer value) {
                    this.visible = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="Left" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
             *       &lt;attribute name="Top" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
             *       &lt;attribute name="Right" type="{http://www.w3.org/2001/XMLSchema}int" default="1900" />
             *       &lt;attribute name="Bottom" type="{http://www.w3.org/2001/XMLSchema}int" default="1100" />
             *       &lt;attribute name="Maximized" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Pos {

                @XmlAttribute(name = "Left")
                protected Integer left;
                @XmlAttribute(name = "Top")
                protected Integer top;
                @XmlAttribute(name = "Right")
                protected Integer right;
                @XmlAttribute(name = "Bottom")
                protected Integer bottom;
                @XmlAttribute(name = "Maximized")
                protected Integer maximized;

                /**
                 * Gets the value of the left property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public int getLeft() {
                    if (left == null) {
                        return  0;
                    } else {
                        return left;
                    }
                }

                /**
                 * Sets the value of the left property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setLeft(Integer value) {
                    this.left = value;
                }

                /**
                 * Gets the value of the top property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public int getTop() {
                    if (top == null) {
                        return  0;
                    } else {
                        return top;
                    }
                }

                /**
                 * Sets the value of the top property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setTop(Integer value) {
                    this.top = value;
                }

                /**
                 * Gets the value of the right property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public int getRight() {
                    if (right == null) {
                        return  1900;
                    } else {
                        return right;
                    }
                }

                /**
                 * Sets the value of the right property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setRight(Integer value) {
                    this.right = value;
                }

                /**
                 * Gets the value of the bottom property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public int getBottom() {
                    if (bottom == null) {
                        return  1100;
                    } else {
                        return bottom;
                    }
                }

                /**
                 * Sets the value of the bottom property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setBottom(Integer value) {
                    this.bottom = value;
                }

                /**
                 * Gets the value of the maximized property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public int getMaximized() {
                    if (maximized == null) {
                        return  0;
                    } else {
                        return maximized;
                    }
                }

                /**
                 * Sets the value of the maximized property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setMaximized(Integer value) {
                    this.maximized = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="Visible" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
             *       &lt;attribute name="Width" type="{http://www.w3.org/2001/XMLSchema}int" default="240" />
             *       &lt;attribute name="Height" type="{http://www.w3.org/2001/XMLSchema}int" default="1050" />
             *       &lt;attribute name="Dock" type="{http://www.w3.org/2001/XMLSchema}string" default="Left" />
             *       &lt;attribute name="Autohide" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class ServersBox {

                @XmlAttribute(name = "Visible")
                protected Integer visible;
                @XmlAttribute(name = "Width")
                protected Integer width;
                @XmlAttribute(name = "Height")
                protected Integer height;
                @XmlAttribute(name = "Dock")
                protected String dock;
                @XmlAttribute(name = "Autohide")
                protected Integer autohide;

                /**
                 * Gets the value of the visible property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public int getVisible() {
                    if (visible == null) {
                        return  1;
                    } else {
                        return visible;
                    }
                }

                /**
                 * Sets the value of the visible property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setVisible(Integer value) {
                    this.visible = value;
                }

                /**
                 * Gets the value of the width property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public int getWidth() {
                    if (width == null) {
                        return  240;
                    } else {
                        return width;
                    }
                }

                /**
                 * Sets the value of the width property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setWidth(Integer value) {
                    this.width = value;
                }

                /**
                 * Gets the value of the height property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public int getHeight() {
                    if (height == null) {
                        return  1050;
                    } else {
                        return height;
                    }
                }

                /**
                 * Sets the value of the height property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setHeight(Integer value) {
                    this.height = value;
                }

                /**
                 * Gets the value of the dock property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDock() {
                    if (dock == null) {
                        return "Left";
                    } else {
                        return dock;
                    }
                }

                /**
                 * Sets the value of the dock property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDock(String value) {
                    this.dock = value;
                }

                /**
                 * Gets the value of the autohide property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public int getAutohide() {
                    if (autohide == null) {
                        return  0;
                    } else {
                        return autohide;
                    }
                }

                /**
                 * Sets the value of the autohide property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setAutohide(Integer value) {
                    this.autohide = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="HideOnTab" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class StartPage {

                @XmlAttribute(name = "HideOnTab")
                protected Integer hideOnTab;

                /**
                 * Gets the value of the hideOnTab property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public int getHideOnTab() {
                    if (hideOnTab == null) {
                        return  0;
                    } else {
                        return hideOnTab;
                    }
                }

                /**
                 * Sets the value of the hideOnTab property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setHideOnTab(Integer value) {
                    this.hideOnTab = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="Visible" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Toolbar {

                @XmlAttribute(name = "Visible")
                protected Integer visible;

                /**
                 * Gets the value of the visible property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public int getVisible() {
                    if (visible == null) {
                        return  1;
                    } else {
                        return visible;
                    }
                }

                /**
                 * Sets the value of the visible property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setVisible(Integer value) {
                    this.visible = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NextTab" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="PrevTab" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="AppSwitch" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="acPuttyLocations" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="acSettings" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="acHideServers" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="acHideMenu" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="acHideToolbar" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="acAddServer" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="acAddGroup" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="acRemove" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="acDetach" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="acConnect" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="acConnectTo" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="acTreeProps" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="acSendScript" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="acAttach" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="acRenameTab" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="acImportTree" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="acExportTree" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="acHotkeyMap" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="acDuplicate" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nextTab",
        "prevTab",
        "appSwitch",
        "acPuttyLocations",
        "acSettings",
        "acHideServers",
        "acHideMenu",
        "acHideToolbar",
        "acAddServer",
        "acAddGroup",
        "acRemove",
        "acDetach",
        "acConnect",
        "acConnectTo",
        "acTreeProps",
        "acSendScript",
        "acAttach",
        "acRenameTab",
        "acImportTree",
        "acExportTree",
        "acHotkeyMap",
        "acDuplicate"
    })
    public static class Hotkeys {

        @XmlElement(name = "NextTab", defaultValue = "0")
        protected int nextTab;
        @XmlElement(name = "PrevTab", defaultValue = "0")
        protected int prevTab;
        @XmlElement(name = "AppSwitch", defaultValue = "16576")
        protected int appSwitch;
        @XmlElement(defaultValue = "0")
        protected int acPuttyLocations;
        @XmlElement(defaultValue = "0")
        protected int acSettings;
        @XmlElement(defaultValue = "16450")
        protected int acHideServers;
        @XmlElement(defaultValue = "16461")
        protected int acHideMenu;
        @XmlElement(defaultValue = "16468")
        protected int acHideToolbar;
        @XmlElement(defaultValue = "0")
        protected int acAddServer;
        @XmlElement(defaultValue = "0")
        protected int acAddGroup;
        @XmlElement(defaultValue = "0")
        protected int acRemove;
        @XmlElement(defaultValue = "0")
        protected int acDetach;
        @XmlElement(defaultValue = "0")
        protected int acConnect;
        @XmlElement(defaultValue = "16459")
        protected int acConnectTo;
        @XmlElement(defaultValue = "0")
        protected int acTreeProps;
        @XmlElement(defaultValue = "0")
        protected int acSendScript;
        @XmlElement(defaultValue = "0")
        protected int acAttach;
        @XmlElement(defaultValue = "0")
        protected int acRenameTab;
        @XmlElement(defaultValue = "0")
        protected int acImportTree;
        @XmlElement(defaultValue = "0")
        protected int acExportTree;
        @XmlElement(defaultValue = "0")
        protected int acHotkeyMap;
        @XmlElement(defaultValue = "0")
        protected int acDuplicate;

        /**
         * Gets the value of the nextTab property.
         * 
         */
        public int getNextTab() {
            return nextTab;
        }

        /**
         * Sets the value of the nextTab property.
         * 
         */
        public void setNextTab(int value) {
            this.nextTab = value;
        }

        /**
         * Gets the value of the prevTab property.
         * 
         */
        public int getPrevTab() {
            return prevTab;
        }

        /**
         * Sets the value of the prevTab property.
         * 
         */
        public void setPrevTab(int value) {
            this.prevTab = value;
        }

        /**
         * Gets the value of the appSwitch property.
         * 
         */
        public int getAppSwitch() {
            return appSwitch;
        }

        /**
         * Sets the value of the appSwitch property.
         * 
         */
        public void setAppSwitch(int value) {
            this.appSwitch = value;
        }

        /**
         * Gets the value of the acPuttyLocations property.
         * 
         */
        public int getAcPuttyLocations() {
            return acPuttyLocations;
        }

        /**
         * Sets the value of the acPuttyLocations property.
         * 
         */
        public void setAcPuttyLocations(int value) {
            this.acPuttyLocations = value;
        }

        /**
         * Gets the value of the acSettings property.
         * 
         */
        public int getAcSettings() {
            return acSettings;
        }

        /**
         * Sets the value of the acSettings property.
         * 
         */
        public void setAcSettings(int value) {
            this.acSettings = value;
        }

        /**
         * Gets the value of the acHideServers property.
         * 
         */
        public int getAcHideServers() {
            return acHideServers;
        }

        /**
         * Sets the value of the acHideServers property.
         * 
         */
        public void setAcHideServers(int value) {
            this.acHideServers = value;
        }

        /**
         * Gets the value of the acHideMenu property.
         * 
         */
        public int getAcHideMenu() {
            return acHideMenu;
        }

        /**
         * Sets the value of the acHideMenu property.
         * 
         */
        public void setAcHideMenu(int value) {
            this.acHideMenu = value;
        }

        /**
         * Gets the value of the acHideToolbar property.
         * 
         */
        public int getAcHideToolbar() {
            return acHideToolbar;
        }

        /**
         * Sets the value of the acHideToolbar property.
         * 
         */
        public void setAcHideToolbar(int value) {
            this.acHideToolbar = value;
        }

        /**
         * Gets the value of the acAddServer property.
         * 
         */
        public int getAcAddServer() {
            return acAddServer;
        }

        /**
         * Sets the value of the acAddServer property.
         * 
         */
        public void setAcAddServer(int value) {
            this.acAddServer = value;
        }

        /**
         * Gets the value of the acAddGroup property.
         * 
         */
        public int getAcAddGroup() {
            return acAddGroup;
        }

        /**
         * Sets the value of the acAddGroup property.
         * 
         */
        public void setAcAddGroup(int value) {
            this.acAddGroup = value;
        }

        /**
         * Gets the value of the acRemove property.
         * 
         */
        public int getAcRemove() {
            return acRemove;
        }

        /**
         * Sets the value of the acRemove property.
         * 
         */
        public void setAcRemove(int value) {
            this.acRemove = value;
        }

        /**
         * Gets the value of the acDetach property.
         * 
         */
        public int getAcDetach() {
            return acDetach;
        }

        /**
         * Sets the value of the acDetach property.
         * 
         */
        public void setAcDetach(int value) {
            this.acDetach = value;
        }

        /**
         * Gets the value of the acConnect property.
         * 
         */
        public int getAcConnect() {
            return acConnect;
        }

        /**
         * Sets the value of the acConnect property.
         * 
         */
        public void setAcConnect(int value) {
            this.acConnect = value;
        }

        /**
         * Gets the value of the acConnectTo property.
         * 
         */
        public int getAcConnectTo() {
            return acConnectTo;
        }

        /**
         * Sets the value of the acConnectTo property.
         * 
         */
        public void setAcConnectTo(int value) {
            this.acConnectTo = value;
        }

        /**
         * Gets the value of the acTreeProps property.
         * 
         */
        public int getAcTreeProps() {
            return acTreeProps;
        }

        /**
         * Sets the value of the acTreeProps property.
         * 
         */
        public void setAcTreeProps(int value) {
            this.acTreeProps = value;
        }

        /**
         * Gets the value of the acSendScript property.
         * 
         */
        public int getAcSendScript() {
            return acSendScript;
        }

        /**
         * Sets the value of the acSendScript property.
         * 
         */
        public void setAcSendScript(int value) {
            this.acSendScript = value;
        }

        /**
         * Gets the value of the acAttach property.
         * 
         */
        public int getAcAttach() {
            return acAttach;
        }

        /**
         * Sets the value of the acAttach property.
         * 
         */
        public void setAcAttach(int value) {
            this.acAttach = value;
        }

        /**
         * Gets the value of the acRenameTab property.
         * 
         */
        public int getAcRenameTab() {
            return acRenameTab;
        }

        /**
         * Sets the value of the acRenameTab property.
         * 
         */
        public void setAcRenameTab(int value) {
            this.acRenameTab = value;
        }

        /**
         * Gets the value of the acImportTree property.
         * 
         */
        public int getAcImportTree() {
            return acImportTree;
        }

        /**
         * Sets the value of the acImportTree property.
         * 
         */
        public void setAcImportTree(int value) {
            this.acImportTree = value;
        }

        /**
         * Gets the value of the acExportTree property.
         * 
         */
        public int getAcExportTree() {
            return acExportTree;
        }

        /**
         * Sets the value of the acExportTree property.
         * 
         */
        public void setAcExportTree(int value) {
            this.acExportTree = value;
        }

        /**
         * Gets the value of the acHotkeyMap property.
         * 
         */
        public int getAcHotkeyMap() {
            return acHotkeyMap;
        }

        /**
         * Sets the value of the acHotkeyMap property.
         * 
         */
        public void setAcHotkeyMap(int value) {
            this.acHotkeyMap = value;
        }

        /**
         * Gets the value of the acDuplicate property.
         * 
         */
        public int getAcDuplicate() {
            return acDuplicate;
        }

        /**
         * Sets the value of the acDuplicate property.
         * 
         */
        public void setAcDuplicate(int value) {
            this.acDuplicate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Putty" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "putty"
    })
    public static class Internals {

        @XmlElement(name = "Putty", required = true)
        protected Object putty;

        /**
         * Gets the value of the putty property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getPutty() {
            return putty;
        }

        /**
         * Sets the value of the putty property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setPutty(Object value) {
            this.putty = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PuttyCon" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "puttyCon"
    })
    public static class Recents {

        @XmlElement(name = "PuttyCon", required = true)
        protected Object puttyCon;

        /**
         * Gets the value of the puttyCon property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getPuttyCon() {
            return puttyCon;
        }

        /**
         * Sets the value of the puttyCon property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setPuttyCon(Object value) {
            this.puttyCon = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Putty">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Node" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="SavedSession" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="DisplayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ServerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="PuttyConType" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="Port" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="PasswordDelay" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="CLParams" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ScriptDelay" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "putty"
    })
    public static class Servers {

        @XmlElement(name = "Putty", required = true)
        protected MTPutty.Servers.Putty putty;

        /**
         * Gets the value of the putty property.
         * 
         * @return
         *     possible object is
         *     {@link MTPutty.Servers.Putty }
         *     
         */
        public MTPutty.Servers.Putty getPutty() {
            return putty;
        }

        /**
         * Sets the value of the putty property.
         * 
         * @param value
         *     allowed object is
         *     {@link MTPutty.Servers.Putty }
         *     
         */
        public void setPutty(MTPutty.Servers.Putty value) {
            this.putty = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Node" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="SavedSession" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="DisplayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ServerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="PuttyConType" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="Port" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="PasswordDelay" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="CLParams" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ScriptDelay" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "node"
        })
        public static class Putty {

            @XmlElement(name = "Node", required = true)
            protected List<MTPutty.Servers.Putty.Node> node;

            /**
             * Gets the value of the node property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the node property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getNode().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link MTPutty.Servers.Putty.Node }
             * 
             * 
             */
            public List<MTPutty.Servers.Putty.Node> getNode() {
                if (node == null) {
                    node = new ArrayList<MTPutty.Servers.Putty.Node>();
                }
                return this.node;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="SavedSession" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="DisplayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ServerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="PuttyConType" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="Port" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="PasswordDelay" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="CLParams" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ScriptDelay" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *       &lt;/sequence>
             *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "savedSession",
                "displayName",
                "serverName",
                "puttyConType",
                "port",
                "userName",
                "password",
                "passwordDelay",
                "clParams",
                "scriptDelay"
            })
            public static class Node {

                @XmlElement(name = "SavedSession", required = true, defaultValue = "Default Settings")
                protected String savedSession;
                @XmlElement(name = "DisplayName", required = true)
                protected String displayName;
                @XmlElement(name = "ServerName", required = true)
                protected String serverName;
                @XmlElement(name = "PuttyConType")
                protected int puttyConType;
                @XmlElement(name = "Port")
                protected int port;
                @XmlElement(name = "UserName", required = true)
                protected String userName;
                @XmlElement(name = "Password", required = true)
                protected String password;
                @XmlElement(name = "PasswordDelay", defaultValue = "0")
                protected int passwordDelay;
                @XmlElement(name = "CLParams", required = true)
                protected String clParams;
                @XmlElement(name = "ScriptDelay", defaultValue = "0")
                protected int scriptDelay;
                @XmlAttribute(name = "Type")
                protected Integer type;

                /**
                 * Gets the value of the savedSession property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSavedSession() {
                    return savedSession;
                }

                /**
                 * Sets the value of the savedSession property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSavedSession(String value) {
                    this.savedSession = value;
                }

                /**
                 * Gets the value of the displayName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDisplayName() {
                    return displayName;
                }

                /**
                 * Sets the value of the displayName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDisplayName(String value) {
                    this.displayName = value;
                }

                /**
                 * Gets the value of the serverName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getServerName() {
                    return serverName;
                }

                /**
                 * Sets the value of the serverName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setServerName(String value) {
                    this.serverName = value;
                }

                /**
                 * Gets the value of the puttyConType property.
                 * 
                 */
                public int getPuttyConType() {
                    return puttyConType;
                }

                /**
                 * Sets the value of the puttyConType property.
                 * 
                 */
                public void setPuttyConType(int value) {
                    this.puttyConType = value;
                }

                /**
                 * Gets the value of the port property.
                 * 
                 */
                public int getPort() {
                    return port;
                }

                /**
                 * Sets the value of the port property.
                 * 
                 */
                public void setPort(int value) {
                    this.port = value;
                }

                /**
                 * Gets the value of the userName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUserName() {
                    return userName;
                }

                /**
                 * Sets the value of the userName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUserName(String value) {
                    this.userName = value;
                }

                /**
                 * Gets the value of the password property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPassword() {
                    return password;
                }

                /**
                 * Sets the value of the password property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPassword(String value) {
                    this.password = value;
                }

                /**
                 * Gets the value of the passwordDelay property.
                 * 
                 */
                public int getPasswordDelay() {
                    return passwordDelay;
                }

                /**
                 * Sets the value of the passwordDelay property.
                 * 
                 */
                public void setPasswordDelay(int value) {
                    this.passwordDelay = value;
                }

                /**
                 * Gets the value of the clParams property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCLParams() {
                    return clParams;
                }

                /**
                 * Sets the value of the clParams property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCLParams(String value) {
                    this.clParams = value;
                }

                /**
                 * Gets the value of the scriptDelay property.
                 * 
                 */
                public int getScriptDelay() {
                    return scriptDelay;
                }

                /**
                 * Sets the value of the scriptDelay property.
                 * 
                 */
                public void setScriptDelay(int value) {
                    this.scriptDelay = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setType(Integer value) {
                    this.type = value;
                }

            }

        }

    }

}
