//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.09 at 07:55:29 PM EDT 
//


package gov.sbs.devops.puttygenerator.mtputty;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MTPutty }
     * 
     */
    public MTPutty createMTPutty() {
        return new MTPutty();
    }

    /**
     * Create an instance of {@link MTPutty.Servers }
     * 
     */
    public MTPutty.Servers createMTPuttyServers() {
        return new MTPutty.Servers();
    }

    /**
     * Create an instance of {@link MTPutty.Servers.Putty }
     * 
     */
    public MTPutty.Servers.Putty createMTPuttyServersPutty() {
        return new MTPutty.Servers.Putty();
    }

    /**
     * Create an instance of {@link MTPutty.Globals }
     * 
     */
    public MTPutty.Globals createMTPuttyGlobals() {
        return new MTPutty.Globals();
    }

    /**
     * Create an instance of {@link MTPutty.Globals.GUI }
     * 
     */
    public MTPutty.Globals.GUI createMTPuttyGlobalsGUI() {
        return new MTPutty.Globals.GUI();
    }

    /**
     * Create an instance of {@link MTPutty.Internals }
     * 
     */
    public MTPutty.Internals createMTPuttyInternals() {
        return new MTPutty.Internals();
    }

    /**
     * Create an instance of {@link MTPutty.Recents }
     * 
     */
    public MTPutty.Recents createMTPuttyRecents() {
        return new MTPutty.Recents();
    }

    /**
     * Create an instance of {@link MTPutty.Hotkeys }
     * 
     */
    public MTPutty.Hotkeys createMTPuttyHotkeys() {
        return new MTPutty.Hotkeys();
    }

    /**
     * Create an instance of {@link MTPutty.Servers.Putty.Node }
     * 
     */
    public MTPutty.Servers.Putty.Node createMTPuttyServersPuttyNode() {
        return new MTPutty.Servers.Putty.Node();
    }

    /**
     * Create an instance of {@link MTPutty.Globals.General }
     * 
     */
    public MTPutty.Globals.General createMTPuttyGlobalsGeneral() {
        return new MTPutty.Globals.General();
    }

    /**
     * Create an instance of {@link MTPutty.Globals.GUI.Pos }
     * 
     */
    public MTPutty.Globals.GUI.Pos createMTPuttyGlobalsGUIPos() {
        return new MTPutty.Globals.GUI.Pos();
    }

    /**
     * Create an instance of {@link MTPutty.Globals.GUI.ServersBox }
     * 
     */
    public MTPutty.Globals.GUI.ServersBox createMTPuttyGlobalsGUIServersBox() {
        return new MTPutty.Globals.GUI.ServersBox();
    }

    /**
     * Create an instance of {@link MTPutty.Globals.GUI.Toolbar }
     * 
     */
    public MTPutty.Globals.GUI.Toolbar createMTPuttyGlobalsGUIToolbar() {
        return new MTPutty.Globals.GUI.Toolbar();
    }

    /**
     * Create an instance of {@link MTPutty.Globals.GUI.MainMenu }
     * 
     */
    public MTPutty.Globals.GUI.MainMenu createMTPuttyGlobalsGUIMainMenu() {
        return new MTPutty.Globals.GUI.MainMenu();
    }

    /**
     * Create an instance of {@link MTPutty.Globals.GUI.StartPage }
     * 
     */
    public MTPutty.Globals.GUI.StartPage createMTPuttyGlobalsGUIStartPage() {
        return new MTPutty.Globals.GUI.StartPage();
    }

}
