//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.09 at 08:06:19 PM EDT 
//


package gov.sbs.devops.puttygenerator.filezilla;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Servers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Server" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Host" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Port" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="Protocol" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="User" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Logontype" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="TimezoneOffset" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PasvMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="MaximumMultipleConnections" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="EncodingType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="BypassProxy" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="LocalDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="RemoteDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SyncBrowsing" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ValueHost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="timestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "servers"
})
@XmlRootElement(name = "FileZilla3")
public class FileZilla3 {

    @XmlElement(name = "Servers", required = true)
    protected FileZilla3 .Servers servers;
    @XmlAttribute(required = true)
    protected String version;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;

    /**
     * Gets the value of the servers property.
     * 
     * @return
     *     possible object is
     *     {@link FileZilla3 .Servers }
     *     
     */
    public FileZilla3 .Servers getServers() {
        return servers;
    }

    /**
     * Sets the value of the servers property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileZilla3 .Servers }
     *     
     */
    public void setServers(FileZilla3 .Servers value) {
        this.servers = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Server" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Host" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Port" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="Protocol" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="User" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Logontype" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="TimezoneOffset" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PasvMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="MaximumMultipleConnections" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="EncodingType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="BypassProxy" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="LocalDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="RemoteDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SyncBrowsing" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ValueHost" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "server"
    })
    public static class Servers {

        @XmlElement(name = "Server", required = true)
        protected List<FileZilla3 .Servers.Server> server;
        @XmlAttribute(required = true)
        protected String name;

        /**
         * Gets the value of the server property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the server property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getServer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FileZilla3 .Servers.Server }
         * 
         * 
         */
        public List<FileZilla3 .Servers.Server> getServer() {
            if (server == null) {
                server = new ArrayList<FileZilla3 .Servers.Server>();
            }
            return this.server;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Host" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Port" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="Protocol" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="User" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Logontype" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="TimezoneOffset" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PasvMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="MaximumMultipleConnections" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="EncodingType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="BypassProxy" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="LocalDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="RemoteDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SyncBrowsing" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ValueHost" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "host",
            "port",
            "protocol",
            "type",
            "user",
            "logontype",
            "timezoneOffset",
            "pasvMode",
            "maximumMultipleConnections",
            "encodingType",
            "bypassProxy",
            "name",
            "comments",
            "localDir",
            "remoteDir",
            "syncBrowsing",
            "valueHost"
        })
        public static class Server {

            @XmlElement(name = "Host", required = true)
            protected String host;
            @XmlElement(name = "Port")
            protected int port;
            @XmlElement(name = "Protocol")
            protected int protocol;
            @XmlElement(name = "Type")
            protected int type;
            @XmlElement(name = "User", required = true)
            protected String user;
            @XmlElement(name = "Logontype")
            protected int logontype;
            @XmlElement(name = "TimezoneOffset", required = true)
            protected String timezoneOffset;
            @XmlElement(name = "PasvMode", required = true)
            protected String pasvMode;
            @XmlElement(name = "MaximumMultipleConnections")
            protected int maximumMultipleConnections;
            @XmlElement(name = "EncodingType", required = true)
            protected String encodingType;
            @XmlElement(name = "BypassProxy")
            protected int bypassProxy;
            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(name = "Comments", required = true)
            protected String comments;
            @XmlElement(name = "LocalDir", required = true)
            protected String localDir;
            @XmlElement(name = "RemoteDir", required = true)
            protected String remoteDir;
            @XmlElement(name = "SyncBrowsing")
            protected int syncBrowsing;
            @XmlElement(name = "ValueHost", required = true)
            protected String valueHost;

            /**
             * Gets the value of the host property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHost() {
                return host;
            }

            /**
             * Sets the value of the host property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHost(String value) {
                this.host = value;
            }

            /**
             * Gets the value of the port property.
             * 
             */
            public int getPort() {
                return port;
            }

            /**
             * Sets the value of the port property.
             * 
             */
            public void setPort(int value) {
                this.port = value;
            }

            /**
             * Gets the value of the protocol property.
             * 
             */
            public int getProtocol() {
                return protocol;
            }

            /**
             * Sets the value of the protocol property.
             * 
             */
            public void setProtocol(int value) {
                this.protocol = value;
            }

            /**
             * Gets the value of the type property.
             * 
             */
            public int getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             */
            public void setType(int value) {
                this.type = value;
            }

            /**
             * Gets the value of the user property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUser() {
                return user;
            }

            /**
             * Sets the value of the user property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUser(String value) {
                this.user = value;
            }

            /**
             * Gets the value of the logontype property.
             * 
             */
            public int getLogontype() {
                return logontype;
            }

            /**
             * Sets the value of the logontype property.
             * 
             */
            public void setLogontype(int value) {
                this.logontype = value;
            }

            /**
             * Gets the value of the timezoneOffset property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTimezoneOffset() {
                return timezoneOffset;
            }

            /**
             * Sets the value of the timezoneOffset property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTimezoneOffset(String value) {
                this.timezoneOffset = value;
            }

            /**
             * Gets the value of the pasvMode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPasvMode() {
                return pasvMode;
            }

            /**
             * Sets the value of the pasvMode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPasvMode(String value) {
                this.pasvMode = value;
            }

            /**
             * Gets the value of the maximumMultipleConnections property.
             * 
             */
            public int getMaximumMultipleConnections() {
                return maximumMultipleConnections;
            }

            /**
             * Sets the value of the maximumMultipleConnections property.
             * 
             */
            public void setMaximumMultipleConnections(int value) {
                this.maximumMultipleConnections = value;
            }

            /**
             * Gets the value of the encodingType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEncodingType() {
                return encodingType;
            }

            /**
             * Sets the value of the encodingType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEncodingType(String value) {
                this.encodingType = value;
            }

            /**
             * Gets the value of the bypassProxy property.
             * 
             */
            public int getBypassProxy() {
                return bypassProxy;
            }

            /**
             * Sets the value of the bypassProxy property.
             * 
             */
            public void setBypassProxy(int value) {
                this.bypassProxy = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the comments property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getComments() {
                return comments;
            }

            /**
             * Sets the value of the comments property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setComments(String value) {
                this.comments = value;
            }

            /**
             * Gets the value of the localDir property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocalDir() {
                return localDir;
            }

            /**
             * Sets the value of the localDir property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocalDir(String value) {
                this.localDir = value;
            }

            /**
             * Gets the value of the remoteDir property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRemoteDir() {
                return remoteDir;
            }

            /**
             * Sets the value of the remoteDir property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRemoteDir(String value) {
                this.remoteDir = value;
            }

            /**
             * Gets the value of the syncBrowsing property.
             * 
             */
            public int getSyncBrowsing() {
                return syncBrowsing;
            }

            /**
             * Sets the value of the syncBrowsing property.
             * 
             */
            public void setSyncBrowsing(int value) {
                this.syncBrowsing = value;
            }

            /**
             * Gets the value of the valueHost property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValueHost() {
                return valueHost;
            }

            /**
             * Sets the value of the valueHost property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValueHost(String value) {
                this.valueHost = value;
            }

        }

    }

}
