//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.09 at 08:06:19 PM EDT 
//


package gov.sbs.devops.puttygenerator.filezilla;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.sbs.devops.puttygenerator.filezilla package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.sbs.devops.puttygenerator.filezilla
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FileZilla3 .Servers }
     * 
     */
    public FileZilla3 .Servers createFileZilla3Servers() {
        return new FileZilla3 .Servers();
    }

    /**
     * Create an instance of {@link FileZilla3 .Servers.Server }
     * 
     */
    public FileZilla3 .Servers.Server createFileZilla3ServersServer() {
        return new FileZilla3 .Servers.Server();
    }

    /**
     * Create an instance of {@link FileZilla3 }
     * 
     */
    public FileZilla3 createFileZilla3() {
        return new FileZilla3();
    }

}
